services:

  db:
    image: postgres
    restart: always
 
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: sase-db
    ports:
      - 5555:5432 
      
    networks:
      sase_network:
        ipv4_address: 194.20.1.29

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    
    environment:
      PGADMIN_DEFAULT_EMAIL: user@sadsecurity.it
      PGADMIN_DEFAULT_PASSWORD:  password
    ports:
      - 5051:80   
    networks:
      sase_network:
        ipv4_address: 194.20.1.41

  docker-manager:
    image: veturo98/server-python:latest
    restart: always
    volumes:
      - ./server.py:/home/ubuntu/server.py

    command: bash -c "cd /home/ubuntu && apt update && apt upgrade -y && python3 server.py"

    ports:
      - 2222:8080

networks:
  sase_network:
    ipam:
      config:
        - subnet: 194.20.1.0/24
