services:

  db:
    image: postgres
    restart: always
 
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: sase-db
    ports:
      - 5555:5432 
      
    networks:
      sase_db_network:
        ipv4_address: 194.20.1.29

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    
    environment:
      PGADMIN_DEFAULT_EMAIL: user@sadsecurity.it
      PGADMIN_DEFAULT_PASSWORD:  password
    ports:
      - 5051:80   
    networks:
      sase_db_network:
        ipv4_address: 194.20.1.41
        
  gestore-risorse:
    image: veturo98/server-python:latest
    working_dir: /home/ubuntu/server-python
    command: "python3 server.py"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1234:1234
    networks:
      sase_network:
        ipv4_address: 10.10.1.3
  
  sase:
    image: veturo98/sase:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sase-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      sase_db_network:
        ipv4_address: 194.20.1.51
      sase_network:
        ipv4_address: 10.10.1.2


  
networks:
  sase_db_network:
    ipam:
      config:
        - subnet: 194.20.1.0/24
  sase_network:
    ipam:
      config:
        - subnet: 10.10.1.0/24
  
